spring:
  application:
    name: eureka-server
    
server:
  port: 8001
  
eureka:
  instance:
    prefer-ip-address: true
    hostname: localhost
  server:
    enable-self-preservation: false  
  client:
    register-with-eureka: false #代表不向注册中心注册自己。
    fetch-registry: false #它并不需要去检索服务
    service-url:
       defaultZone: http://127.0.0.2:8001/eureka/

